In [41]:
import torch
import torch.nn as nn

In [42]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]], dtype=torch.float32)

In [43]:
print(a)
print(b)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])


In [44]:
cos = nn.CosineSimilarity(dim=0)


In [45]:
b_len = torch.sqrt(torch.sum(torch.mul(b, b), 1))
print(b_len)

tensor([3.7417, 5.3852, 7.0711])


In [46]:
a_len = torch.sqrt(torch.sum(torch.mul(a, a)))
print(a_len)

tensor(3.7417)


In [47]:
# 两模相乘，分母
ab_len = torch.mul(a_len, b_len)
print(ab_len)

tensor([14.0000, 20.1494, 26.4575])


In [48]:
print(torch.mul(a, b))
# 两向量内积，分子
ab_dist = torch.sum(torch.mul(a, b), 1)
print(ab_dist)


tensor([[ 1.,  4.,  9.],
        [ 2.,  6., 12.],
        [ 3.,  8., 15.]])
tensor([14., 20., 26.])


In [49]:
res = torch.div(ab_dist, ab_len)
print(res)

tensor([1.0000, 0.9926, 0.9827])


In [50]:
cos = nn.CosineSimilarity(dim = 1)
cos(a,b)

tensor([1.0000, 0.9926, 0.9827])

In [59]:
res.argmax().item()

0